"""Database package: schema contract and verification helpers."""

from app.db.schema_contract import (
    APPLICATION_REQUIRED_COLUMNS,
    APPLICATION_REQUIRED_FOREIGN_KEYS,
    APPLICATION_REQUIRED_TABLES,
    EMBEDDING_VECTOR_DIMENSIONS,
    MIGRATION_FILES,
)

__all__ = [
    "APPLICATION_REQUIRED_COLUMNS",
    "APPLICATION_REQUIRED_FOREIGN_KEYS",
    "APPLICATION_REQUIRED_TABLES",
    "EMBEDDING_VECTOR_DIMENSIONS",
    "MIGRATION_FILES",
]
